import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Barzar(),
        ]),
      ),
    );
  }
}

class Barzar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 797,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 81,
                child: Container(
                  width: 452,
                  height: 21,
                  padding: const EdgeInsets.only(left: 20),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                ),
              ),
              Positioned(
                left: 41,
                top: 61,
                child: Container(
                  width: 294,
                  height: 43,
                  padding: const EdgeInsets.symmetric(horizontal: 13, vertical: 4),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF15654E),
                      ),
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 15,
                    children: [
                      SizedBox(
                        width: 52,
                        height: 23,
                        child: Text(
                          'search',
                          style: TextStyle(
                            color: const Color(0xFF15654E),
                            fontSize: 15,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 308,
                child: Container(
                  width: 153,
                  padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF007E2F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35.92),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 13.31,
                    children: [
                      Text(
                        'Add to Cart',
                        style: TextStyle(
                          color: const Color(0xFFFCFCFC),
                          fontSize: 21.29,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 1.50,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 247,
                child: SizedBox(
                  width: 125,
                  height: 31,
                  child: Text(
                    'seawead',
                    style: TextStyle(
                      color: const Color(0xFF505050),
                      fontSize: 26.61,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 1.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 276,
                child: Text(
                  '₹100',
                  style: TextStyle(
                    color: const Color(0xFF505050),
                    fontSize: 23.95,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 219,
                top: 308,
                child: Container(
                  width: 153,
                  height: 53.29,
                  padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF007E2F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35.92),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 13.31,
                    children: [
                      Text(
                        'Add to Cart',
                        style: TextStyle(
                          color: const Color(0xFFFCFCFC),
                          fontSize: 21.29,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 1.50,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 8,
                top: 626,
                child: Container(
                  width: 153,
                  height: 53.29,
                  padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF007E2F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35.92),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 13.31,
                    children: [
                      Text(
                        'Add to Cart',
                        style: TextStyle(
                          color: const Color(0xFFFCFCFC),
                          fontSize: 21.29,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 1.50,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 213,
                top: 626,
                child: Container(
                  width: 153,
                  height: 53.29,
                  padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF007E2F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35.92),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 13.31,
                    children: [
                      Text(
                        'Add to Cart',
                        style: TextStyle(
                          color: const Color(0xFFFCFCFC),
                          fontSize: 21.29,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 1.50,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 235,
                top: 245,
                child: Text(
                  'seeds',
                  style: TextStyle(
                    color: const Color(0xFF505050),
                    fontSize: 26.61,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 235,
                top: 276,
                child: Text(
                  '₹250',
                  style: TextStyle(
                    color: const Color(0xFF505050),
                    fontSize: 23.95,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 399,
                child: Container(
                  width: 139,
                  height: 173,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/139x173"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 591,
                child: Text(
                  '₹300',
                  style: TextStyle(
                    color: const Color(0xFF282323),
                    fontSize: 23.95,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 235,
                top: 590,
                child: Text(
                  '₹550',
                  style: TextStyle(
                    color: const Color(0xFF282323),
                    fontSize: 23.95,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 565,
                child: SizedBox(
                  width: 147,
                  child: Text(
                    'fertlizer',
                    style: TextStyle(
                      color: const Color(0xFF282323),
                      fontSize: 23.95,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 236,
                top: 565,
                child: SizedBox(
                  width: 99,
                  child: Text(
                    'fertlizer',
                    style: TextStyle(
                      color: const Color(0xFF282323),
                      fontSize: 23.95,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 1.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 338,
                top: 54,
                child: Container(width: 43, height: 43, child: Stack()),
              ),
              Positioned(
                left: 245,
                top: 110,
                child: Container(
                  width: 108.79,
                  height: 149,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/109x149"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 112,
                child: Container(
                  width: 95.31,
                  height: 147,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/95x147"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 241,
                top: 399,
                child: Container(
                  width: 124.51,
                  height: 177,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/125x177"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -27,
                top: 115,
                child: Container(width: 124, height: 184),
              ),
              Positioned(
                left: 574,
                top: -972,
                child: Container(
                  width: 393,
                  height: 687,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 16,
                        child: Container(
                          width: 165.36,
                          height: 226,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/165x226"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 197,
                        child: SizedBox(
                          width: 147,
                          child: Text(
                            'fertlizer',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 232,
                        top: 562,
                        child: SizedBox(
                          width: 159,
                          child: Text(
                            'EarthWorms',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 229,
                        child: Text(
                          '₹590',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 235,
                        top: 4,
                        child: Container(
                          width: 157.88,
                          height: 249,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/158x249"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 237,
                        top: 206,
                        child: SizedBox(
                          width: 158,
                          height: 91,
                          child: Text(
                            'Aber fertilizer',
                            style: TextStyle(
                              color: const Color(0xFF141313),
                              fontSize: 21.29,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 283,
                        top: 229,
                        child: Text(
                          '₹500',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: -48,
                        top: 336,
                        child: Container(
                          width: 285,
                          height: 285,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/285x285"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 614,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 207,
                        top: 614,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 220,
                        top: 265,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 265,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 555,
                        child: SizedBox(
                          width: 147,
                          child: Text(
                            'Sprayer',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 38,
                        top: 582,
                        child: Text(
                          '₹550',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 256,
                        top: 582,
                        child: Text(
                          '₹956',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 173,
                        top: 335,
                        child: Container(
                          width: 241.18,
                          height: 270,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/241x270"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 854,
                child: Container(
                  width: 393,
                  height: 849,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 16,
                        child: Container(
                          width: 165.36,
                          height: 226,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/165x226"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 246,
                        child: SizedBox(
                          width: 147,
                          child: Text(
                            'fertlizer',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 232,
                        top: 675,
                        child: SizedBox(
                          width: 159,
                          child: Text(
                            'EarthWorms',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 278,
                        child: Text(
                          '₹590',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 235,
                        top: 4,
                        child: Container(
                          width: 157.88,
                          height: 249,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/158x249"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 237,
                        top: 255,
                        child: SizedBox(
                          width: 158,
                          height: 91,
                          child: Text(
                            'Aber fertilizer',
                            style: TextStyle(
                              color: const Color(0xFF141313),
                              fontSize: 21.29,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 283,
                        top: 278,
                        child: Text(
                          '₹500',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: -48,
                        top: 401,
                        child: Container(
                          width: 285,
                          height: 285,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/285x285"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 743,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 207,
                        top: 743,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 220,
                        top: 314,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 314,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 684,
                        child: SizedBox(
                          width: 147,
                          child: Text(
                            'Sprayer',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 38,
                        top: 711,
                        child: Text(
                          '₹550',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 256,
                        top: 711,
                        child: Text(
                          '₹956',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 173,
                        top: 416,
                        child: Container(
                          width: 241.18,
                          height: 270,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/241x270"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 806,
                child: Container(
                  width: 393,
                  height: 897,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 16,
                        child: Container(
                          width: 165.36,
                          height: 226,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/165x226"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 260,
                        child: SizedBox(
                          width: 147,
                          child: Text(
                            'fertlizer',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 232,
                        top: 714,
                        child: SizedBox(
                          width: 159,
                          child: Text(
                            'EarthWorms',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 292,
                        child: Text(
                          '₹590',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 235,
                        top: 4,
                        child: Container(
                          width: 157.88,
                          height: 249,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/158x249"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 237,
                        top: 269,
                        child: SizedBox(
                          width: 158,
                          height: 91,
                          child: Text(
                            'Aber fertilizer',
                            style: TextStyle(
                              color: const Color(0xFF141313),
                              fontSize: 21.29,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 283,
                        top: 292,
                        child: Text(
                          '₹500',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: -48,
                        top: 420,
                        child: Container(
                          width: 285,
                          height: 285,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/285x285"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 782,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 207,
                        top: 782,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 220,
                        top: 328,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 328,
                        child: Container(
                          width: 153,
                          padding: const EdgeInsets.symmetric(horizontal: 51.89, vertical: 10.64),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF007E2F),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(35.92),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13.31,
                            children: [
                              Text(
                                'Add to Cart',
                                style: TextStyle(
                                  color: const Color(0xFFFCFCFC),
                                  fontSize: 21.29,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.50,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 723,
                        child: SizedBox(
                          width: 147,
                          child: Text(
                            'Sprayer',
                            style: TextStyle(
                              color: const Color(0xFF282323),
                              fontSize: 23.95,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w700,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 38,
                        top: 750,
                        child: Text(
                          '₹550',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 256,
                        top: 750,
                        child: Text(
                          '₹956',
                          style: TextStyle(
                            color: const Color(0xFF282323),
                            fontSize: 23.95,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 173,
                        top: 440,
                        child: Container(
                          width: 241.18,
                          height: 270,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/241x270"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 835,
                        child: Container(
                          width: 353,
                          padding: const EdgeInsets.symmetric(horizontal: 21, vertical: 18),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1),
                              borderRadius: BorderRadius.circular(50),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Container(
                                padding: const EdgeInsets.all(12),
                                clipBehavior: Clip.antiAlias,
                                decoration: ShapeDecoration(
                                  gradient: LinearGradient(
                                    begin: Alignment(0.50, -0.00),
                                    end: Alignment(0.50, 1.00),
                                    colors: [const Color(0xFF15654E), const Color(0xFF15654E)],
                                  ),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(width: 1, color: Colors.white),
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  shadows: [
                                    BoxShadow(
                                      color: Color(0x3F000000),
                                      blurRadius: 10,
                                      offset: Offset(0, 4),
                                      spreadRadius: 0,
                                    )
                                  ],
                                ),
                                child: Stack(),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
