import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          PopUpWeather(),
        ]),
      ),
    );
  }
}

class PopUpWeather extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 553,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFF2F3F2),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(16),
                topRight: Radius.circular(16),
              ),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 10,
                top: 19,
                child: Container(
                  width: 374,
                  height: 611,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 531,
                        child: Container(
                          width: 374,
                          height: 80,
                          decoration: BoxDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.50, 0.00),
                              end: Alignment(0.50, 1.00),
                              colors: [Colors.white.withValues(alpha: 0), Colors.white],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 12,
                        child: Text(
                          'Condition',
                          style: TextStyle(
                            color: const Color(0xFF15654E),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            letterSpacing: -0.32,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 63,
                child: Container(
                  height: 473,
                  padding: const EdgeInsets.only(bottom: 10),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 27,
                    children: [
                      Container(
                        width: 358,
                        padding: const EdgeInsets.all(12),
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              color: const Color(0xFFE4E7E6),
                            ),
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        child: Stack(
                          children: [
                            SizedBox(
                              width: 334,
                              child: Text(
                                'Normal Level',
                                style: TextStyle(
                                  color: const Color(0xFFFFAB0B),
                                  fontSize: 16,
                                  fontFamily: 'DM Sans',
                                  fontWeight: FontWeight.w500,
                                  height: 1.50,
                                  letterSpacing: -0.32,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 322,
                              top: 12,
                              child: Container(
                                padding: const EdgeInsets.all(4),
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFF2F3F2),
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 4,
                                  children: [
                                    Container(width: 16, height: 16, child: Stack()),
                                  ],
                                ),
                              ),
                            ),
                            Container(
                              width: 334,
                              height: 117.60,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 36,
                                    top: 12,
                                    child: Container(
                                      width: 297.82,
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.end,
                                        spacing: 5.57,
                                        children: [
                                          Opacity(
                                            opacity: 0.20,
                                            child: Expanded(
                                              child: Container(
                                                height: 14.61,
                                                decoration: ShapeDecoration(
                                                  color: const Color(0xFFFFAB0B),
                                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Opacity(
                                            opacity: 0.20,
                                            child: Expanded(
                                              child: Container(
                                                height: 70.28,
                                                decoration: ShapeDecoration(
                                                  color: const Color(0xFFFFAB0B),
                                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Opacity(
                                            opacity: 0.20,
                                            child: Expanded(
                                              child: Container(
                                                height: 38.97,
                                                decoration: ShapeDecoration(
                                                  color: const Color(0xFFFFAB0B),
                                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Expanded(
                                            child: Container(
                                              height: 97.42,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFFFFAB0B),
                                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                              ),
                                            ),
                                          ),
                                          Expanded(
                                            child: Container(
                                              height: 105.77,
                                              child: Column(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.end,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                spacing: 1.39,
                                                children: [
                                                  Opacity(
                                                    opacity: 0.20,
                                                    child: Container(
                                                      width: double.infinity,
                                                      height: 89,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFFFFAB0B),
                                                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                          Opacity(
                                            opacity: 0.20,
                                            child: Expanded(
                                              child: Container(
                                                height: 76.54,
                                                decoration: ShapeDecoration(
                                                  color: const Color(0xFFFFAB0B),
                                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Opacity(
                                            opacity: 0.20,
                                            child: Expanded(
                                              child: Container(
                                                height: 51.49,
                                                decoration: ShapeDecoration(
                                                  color: const Color(0xFFFFAB0B),
                                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: -3.47,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 24.35,
                                      children: [
                                        Text(
                                          '39°',
                                          textAlign: TextAlign.right,
                                          style: TextStyle(
                                            color: const Color(0xFF878787),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 0.80,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                        Text(
                                          '33°',
                                          textAlign: TextAlign.right,
                                          style: TextStyle(
                                            color: const Color(0xFF878787),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 0.80,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                        Text(
                                          '27°',
                                          textAlign: TextAlign.right,
                                          style: TextStyle(
                                            color: const Color(0xFF878787),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 0.80,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                        Text(
                                          '21°',
                                          textAlign: TextAlign.right,
                                          style: TextStyle(
                                            color: const Color(0xFF878787),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 0.80,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              padding: const EdgeInsets.only(top: 8),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 1,
                                    color: const Color(0xFFE4E7E6),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 8,
                                children: [
                                  SizedBox(
                                    width: 32,
                                    child: Text(
                                      'Hour',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: const Color(0xFF0D1814),
                                        fontSize: 14,
                                        fontFamily: 'DM Sans',
                                        fontWeight: FontWeight.w400,
                                        height: 1.43,
                                        letterSpacing: -0.28,
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '00',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '13',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '14',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '15',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '16',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '17',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                  SizedBox(
                                    width: 35.14,
                                    child: Opacity(
                                      opacity: 0.50,
                                      child: Text(
                                        '18',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 358,
                        height: 379,
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          color: Colors.white,
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              color: const Color(0xFFE4E7E6),
                            ),
                            borderRadius: BorderRadius.circular(16),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 43,
                              top: 313,
                              child: Container(
                                width: 685,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFFC3C6C5),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 43,
                              top: 268,
                              child: Container(
                                width: 685,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFFC3C6C5),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 43,
                              top: 223,
                              child: Container(
                                width: 685,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFFC3C6C5),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 43,
                              top: 178,
                              child: Container(
                                width: 685,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFFC3C6C5),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 43,
                              top: 133,
                              child: Container(
                                width: 685,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFFC3C6C5),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 43,
                              top: 88,
                              child: Container(
                                width: 685,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFFC3C6C5),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 200,
                              top: 117,
                              child: Container(
                                transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                                width: 216,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: const Color(0xFF0D1814),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 119,
                              top: 83,
                              child: Container(
                                padding: const EdgeInsets.all(12),
                                decoration: ShapeDecoration(
                                  color: Colors.white,
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                  shadows: [
                                    BoxShadow(
                                      color: Color(0x190D1814),
                                      blurRadius: 16,
                                      offset: Offset(0, 8),
                                      spreadRadius: 0,
                                    )
                                  ],
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 12,
                                  children: [
                                    Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 8,
                                      children: [
                                        Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 6,
                                          children: [
                                            Container(
                                              width: 8,
                                              height: 8,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFF00D0E2),
                                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                              ),
                                            ),
                                            Text(
                                              'Rain',
                                              style: TextStyle(
                                                color: const Color(0xFF0D1814),
                                                fontSize: 12,
                                                fontFamily: 'DM Sans',
                                                fontWeight: FontWeight.w400,
                                                height: 1.17,
                                                letterSpacing: -0.24,
                                              ),
                                            ),
                                          ],
                                        ),
                                        Opacity(
                                          opacity: 0.50,
                                          child: Text(
                                            '41%',
                                            textAlign: TextAlign.right,
                                            style: TextStyle(
                                              color: const Color(0xFF0D1814),
                                              fontSize: 12,
                                              fontFamily: 'DM Sans',
                                              fontWeight: FontWeight.w400,
                                              height: 1.17,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 11,
                              top: 9,
                              child: Container(
                                width: 326,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.only(
                                        top: 8,
                                        left: 12,
                                        right: 12,
                                        bottom: 12,
                                      ),
                                      decoration: ShapeDecoration(
                                        shape: RoundedRectangleBorder(
                                          side: BorderSide(
                                            width: 2,
                                            color: const Color(0xFF427662),
                                          ),
                                        ),
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        spacing: 8,
                                        children: [
                                          Text(
                                            'Chance of Precipitation',
                                            style: TextStyle(
                                              color: const Color(0xFF0D1814),
                                              fontSize: 16,
                                              fontFamily: 'DM Sans',
                                              fontWeight: FontWeight.w400,
                                              height: 1.50,
                                              letterSpacing: -0.32,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 11,
                              top: 332,
                              child: Container(
                                width: 717,
                                padding: const EdgeInsets.only(top: 8),
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFE4E7E6),
                                    ),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 8,
                                  children: [
                                    SizedBox(
                                      width: 32,
                                      child: Text(
                                        'Days',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF0D1814),
                                          fontSize: 14,
                                          fontFamily: 'DM Sans',
                                          fontWeight: FontWeight.w400,
                                          height: 1.43,
                                          letterSpacing: -0.28,
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '1',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '2',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '3',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '4',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '5',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '6',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '7',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '8',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '9',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '10',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '11',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '12',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '13',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '14',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '15',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '16',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '17',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '18',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '19',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                    SizedBox(
                                      width: 26.25,
                                      child: Opacity(
                                        opacity: 0.50,
                                        child: Text(
                                          '20',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF0D1814),
                                            fontSize: 14,
                                            fontFamily: 'DM Sans',
                                            fontWeight: FontWeight.w400,
                                            height: 1.43,
                                            letterSpacing: -0.28,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 11,
                              top: 69,
                              child: Container(
                                width: 32,
                                height: 263,
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 7,
                                  children: [
                                    Expanded(
                                      child: Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 8,
                                          children: [
                                            SizedBox(
                                              width: 32,
                                              child: Opacity(
                                                opacity: 0.50,
                                                child: Text(
                                                  '100',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF0D1814),
                                                    fontSize: 14,
                                                    fontFamily: 'DM Sans',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.43,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Expanded(
                                      child: Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 8,
                                          children: [
                                            SizedBox(
                                              width: 32,
                                              child: Opacity(
                                                opacity: 0.50,
                                                child: Text(
                                                  '80',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF0D1814),
                                                    fontSize: 14,
                                                    fontFamily: 'DM Sans',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.43,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Expanded(
                                      child: Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 8,
                                          children: [
                                            SizedBox(
                                              width: 32,
                                              child: Opacity(
                                                opacity: 0.50,
                                                child: Text(
                                                  '60',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF0D1814),
                                                    fontSize: 14,
                                                    fontFamily: 'DM Sans',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.43,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Expanded(
                                      child: Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 8,
                                          children: [
                                            SizedBox(
                                              width: 32,
                                              child: Opacity(
                                                opacity: 0.50,
                                                child: Text(
                                                  '40',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF0D1814),
                                                    fontSize: 14,
                                                    fontFamily: 'DM Sans',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.43,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Expanded(
                                      child: Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 8,
                                          children: [
                                            SizedBox(
                                              width: 32,
                                              child: Opacity(
                                                opacity: 0.50,
                                                child: Text(
                                                  '20',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF0D1814),
                                                    fontSize: 14,
                                                    fontFamily: 'DM Sans',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.43,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Expanded(
                                      child: Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 8,
                                          children: [
                                            SizedBox(
                                              width: 32,
                                              child: Opacity(
                                                opacity: 0.50,
                                                child: Text(
                                                  '0',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF0D1814),
                                                    fontSize: 14,
                                                    fontFamily: 'DM Sans',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.43,
                                                    letterSpacing: -0.28,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 198,
                              top: 211,
                              child: Container(
                                width: 6,
                                height: 6,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF00D0E2),
                                  shape: OvalBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Colors.white,
                                    ),
                                  ),
                                  shadows: [
                                    BoxShadow(
                                      color: Color(0x330D1814),
                                      blurRadius: 4,
                                      offset: Offset(0, 1),
                                      spreadRadius: 0,
                                    )
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 403,
                              top: 205,
                              child: Container(
                                width: 6,
                                height: 6,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF759B8D),
                                  shape: OvalBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignOutside,
                                      color: Colors.white,
                                    ),
                                  ),
                                  shadows: [
                                    BoxShadow(
                                      color: Color(0x330D1814),
                                      blurRadius: 4,
                                      offset: Offset(0, 1),
                                      spreadRadius: 0,
                                    )
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
