import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ConditionSolutionDetail(),
        ]),
      ),
    );
  }
}

class ConditionSolutionDetail extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 20,
                top: 59,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 60,
                  children: [
                    Text(
                      'Condition & Solution',
                      style: TextStyle(
                        color: const Color(0xFF15654E),
                        fontSize: 20,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 20,
                top: 99,
                child: Container(
                  width: 353,
                  height: 746,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 15,
                    children: [
                      Container(
                        width: 353,
                        height: 235,
                        padding: const EdgeInsets.symmetric(horizontal: 17, vertical: 12),
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          image: DecorationImage(
                            image: NetworkImage("https://placehold.co/353x235"),
                            fit: BoxFit.cover,
                          ),
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                        ),
                      ),
                      SizedBox(
                        width: 357,
                        child: Text(
                          'Impact of Extreme Weather on Tea Plantation Productivity',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Container(
                        height: 1244,
                        padding: const EdgeInsets.only(bottom: 10),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 10,
                          children: [
                            SizedBox(
                              width: 353,
                              height: 2606,
                              child: Text(
                                'Temperatures above 35°C and prolonged drought are a nightmare for tea farmers. These extreme conditions can result in a 40% drop in productivity, dealing a severe blow to their livelihoods and national food security.\n\nHowever, despair is not the way out. Behind this threat lies an opportunity to rise up with innovative and sustainable solutions. Here are some steps that can be taken:\n\n1. Planting Heat-Resistant Varieties:\n\n    Research and development of new tea varieties that are resistant to high temperatures and drought are key.\n    These varieties must have the ability to adapt to changing climatic conditions and still produce high-quality tea shoots.\n\n2. Optimization of Irrigation Systems:\n\n    Implementation of efficient irrigation systems, such as drip irrigation or fertigation, can help maintain soil moisture and optimize water use,\n    This is important to minimize the impact of drought and ensure tea plants get enough water to grow and thrive.\n\n3. Mulching:\n\n    Mulching, which is covering the soil surface with organic matter such as straw or dry grass, can help to retain soil moisture,\n    In addition, mulching can also suppress weed growth and improve soil fertility.\n\nSaving tea plantations from high temperatures and drought requires collective and sustained efforts. With the right solutions and solid cooperation, we can preserve Indonesian tea and improve the welfare of its farmers.\n\nKeep in mind that the above points are just the first step. Further research and development is needed to find the most appropriate and effective solutions for each different tea plantation condition.\n\nThe future of Indonesian tea plantations is in our hands. With determination and hard work, we can turn challenges into opportunities and ensure that Indonesian tea remains a favorite in the international arena.',
                                textAlign: TextAlign.justify,
                                style: TextStyle(
                                  color: const Color(0xFF757575),
                                  fontSize: 15,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.47,
                                  letterSpacing: 0.23,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
